### ISSUE TITLE
进入程序后无法联网

### ISSUE THREAD

**Issue by minesky04** [Co2333/Saily-Store#7]
设备：IPhone 7 plus，IOS13.3,checkra1n越狱，使用Cydia安装这个商店之后，打开程序没有弹出允许联网的申请，设置里也找不到地方允许程序联网

**Comment by Elekoe** [comment]
连个锤子插件，修复国行网络



------------------ 原始邮件 ------------------
发件人: minesky04 <notifications@github.com&gt;
发送时间: 2020年1月18日 22:38
收件人: Co2333/Saily-Store <Saily-Store@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Co2333/Saily-Store] 进入程序后无法联网 (#7)




设备：IPhone 7 plus，IOS13.3,checkra1n越狱，使用Cydia安装这个商店之后，打开程序没有弹出允许联网的申请，设置里也找不到地方允许程序联网

**Comment by Elekoe** [comment]
😄





------------------ 原始邮件 ------------------
发件人: minesky04 <notifications@github.com&gt;
发送时间: 2020年1月20日 22:36
收件人: Co2333/Saily-Store <Saily-Store@noreply.github.com&gt;
抄送: Elekat <gfyond@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Co2333/Saily-Store] 进入程序后无法联网 (#7)




Closed #7.
